/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




#include "STM32F103X6_Drivers.h"
#include "STM32F103x8_gpio_driver.h"


void mywait(int x)
{
   for (int i=0;i<x;i++)
	   for(int j=0;j<255;j++);

}


void clock_init()
{

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

}


void GPIO_Init()
{

	GPIO_PIN_conf_t  GPIOPINCFG;

	//PA1 High z
	GPIOPINCFG.PIN_NUM=GPIO_PIN_1;
	GPIOPINCFG.GPIO_Mode=GPIO_Float_inp_mode;
	GPIOPINCFG.GPIO_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &GPIOPINCFG);


	//PB1 OUTPUT PUSH PULL
	GPIOPINCFG.PIN_NUM=GPIO_PIN_1;
	GPIOPINCFG.GPIO_Mode=GPIO_OUT_PP_mode;
	GPIOPINCFG.GPIO_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &GPIOPINCFG);

	//PA13 Input_High z
	GPIOPINCFG.PIN_NUM=GPIO_PIN_13;
	GPIOPINCFG.GPIO_Mode=GPIO_Float_inp_mode;
	GPIOPINCFG.GPIO_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &GPIOPINCFG);


	//PB13 OUTPUT PUSH PULL
	GPIOPINCFG.PIN_NUM=GPIO_PIN_13;
	GPIOPINCFG.GPIO_Mode=GPIO_OUT_PP_mode;
	GPIOPINCFG.GPIO_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &GPIOPINCFG);


}



int main(void)
{

clock_init();
GPIO_Init();

while(1)
{
   if(MCAL_GPIO_Read_PIN(GPIOA, GPIO_PIN_1)==0)  //PRESS
   {
	   MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
	   while(MCAL_GPIO_Read_PIN(GPIOA, GPIO_PIN_1)==0);   //single press
   }

   if(MCAL_GPIO_Read_PIN(GPIOA, GPIO_PIN_13)==1)
   {
	   MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
   }
   mywait(500);

}


}
