/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stdint.h"
#include "stdlib.h"
#include "stdio.h"

#define RCC_BASE                            0x40021000
#define RCC_APB2ENR                         *(volatile uint32_t *)(RCC_BASE+ 0x18)
#define RCC_IOPAEN                          (1<<2)


//GPIOA BASE ADDRESS

#define GPIOA_BASE                          0x40010800
#define GPIOA_CRL                          *(volatile uint32_t *)(GPIOA_BASE+0x00)
#define GPIOA_CRH                          *(volatile uint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_IDR                          *(volatile uint32_t *)(GPIOA_BASE+0x08)
#define GPIOA_ODR                          *(volatile uint32_t *)(GPIOA_BASE+0x0C)


#define GPIOA13                            (1UL<<13)

//GPIOB BASE ADDRESS

#define GPIOB_BASE                          0x40010C00
#define GPIOB_CRL                          *(volatile uint32_t *)(GPIOB_BASE+0x00)
#define GPIOB_CRH                          *(volatile uint32_t *)(GPIOB_BASE+0x04)
#define GPIOB_IDR                          *(volatile uint32_t *)(GPIOB_BASE+0x08)
#define GPIOB_ODR                          *(volatile uint32_t *)(GPIOB_BASE+0x0C)



void mywait(int x)
{
   for (int i=0;i<x;i++)
	   for(int j=0;j<255;j++);

}


void GPIO_Init()
{

   GPIOA_CRL =0x0;
   GPIOB_CRL =0x0;

   /* set pins A1 & A13  as input floating*/
   GPIOA_CRL |= (1<<6);
   GPIOA_CRH &=~(0b11<<20);
   GPIOA_CRH |=(0b01<<22);

   /* set pins B1 &B 13  as output push pull*/

      GPIOB_CRL &= ~(0b11<<6);
      GPIOB_CRL |= (0b01<<4);

      GPIOB_CRH |=(0b01<<20);
      GPIOB_CRH &=~(0b11<<22);
}

void clk_init()
{
	RCC_APB2ENR |= RCC_IOPAEN;

	RCC_APB2ENR |= (1<<3);
}

int main(void)
{
	clk_init();
	GPIO_Init();


while (1)
{

/* for single pressing*/
if (((GPIOA_IDR & (1<<1))>>1) ==0)
{

   GPIOB_ODR ^= 1<<1;
   while(((GPIOA_IDR & (1<<1))>>1) ==0);

}

/*for multipressing*/
if (((GPIOA_IDR & (1<<13))>>13) ==1)
{
   GPIOB_ODR ^= 1<<13;
}

mywait(1);
}

return 0;
}
